package hibernate.entity;
// Generated Apr 24, 2017 1:01:57 PM by Hibernate Tools 4.3.1



/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer commentId;
     private String commentContent;
     private int commentTdid;
     private String commentCreatedate;
     private String commentLastmodified;
     private Boolean commentStatus;
     private Boolean commentIsread;
     private int commentUserid;

    public Comments() {
    }

	
    public Comments(int commentTdid, int commentUserid) {
        this.commentTdid = commentTdid;
        this.commentUserid = commentUserid;
    }
    public Comments(String commentContent, int commentTdid, String commentCreatedate, String commentLastmodified, Boolean commentStatus, Boolean commentIsread, int commentUserid) {
       this.commentContent = commentContent;
       this.commentTdid = commentTdid;
       this.commentCreatedate = commentCreatedate;
       this.commentLastmodified = commentLastmodified;
       this.commentStatus = commentStatus;
       this.commentIsread = commentIsread;
       this.commentUserid = commentUserid;
    }
   
    public Integer getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }
    public String getCommentContent() {
        return this.commentContent;
    }
    
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }
    public int getCommentTdid() {
        return this.commentTdid;
    }
    
    public void setCommentTdid(int commentTdid) {
        this.commentTdid = commentTdid;
    }
    public String getCommentCreatedate() {
        return this.commentCreatedate;
    }
    
    public void setCommentCreatedate(String commentCreatedate) {
        this.commentCreatedate = commentCreatedate;
    }
    public String getCommentLastmodified() {
        return this.commentLastmodified;
    }
    
    public void setCommentLastmodified(String commentLastmodified) {
        this.commentLastmodified = commentLastmodified;
    }
    public Boolean getCommentStatus() {
        return this.commentStatus;
    }
    
    public void setCommentStatus(Boolean commentStatus) {
        this.commentStatus = commentStatus;
    }
    public Boolean getCommentIsread() {
        return this.commentIsread;
    }
    
    public void setCommentIsread(Boolean commentIsread) {
        this.commentIsread = commentIsread;
    }
    public int getCommentUserid() {
        return this.commentUserid;
    }
    
    public void setCommentUserid(int commentUserid) {
        this.commentUserid = commentUserid;
    }




}


