package hibernate.entity;
// Generated May 17, 2017 4:56:12 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Detai generated by hbm2java
 */
public class Detai implements java.io.Serializable {

    private Integer projectId;
    private Users users;
    private String projectName;
    private String projectContentlink;
    private int projectInstructorid;
    private Integer projectProgress;
    private String projectStartdate;
    private Boolean projectStatus;
    private String projectDescription;
    private Integer projectViewcount;
    private Integer projectPagecount;
    private Boolean projectCancel;
    private Boolean isdelete;
    private String deleteDate;
    private Integer deleteUserid;
    private String detaiResult;
    private String detaiRequest;
    private String detaiSpecialized;
    private Set<Tiendo> tiendos = new HashSet<Tiendo>(0);

    public Detai() {
        projectName="";
        projectContentlink="";
        projectInstructorid=0;
        projectProgress=0;
        projectStartdate="";
        projectStatus=true;
        projectDescription="";
        projectViewcount=0;
        Integer projectPagecount=0;
        projectCancel=false;
        isdelete=false;
        deleteDate="";
        detaiResult="";
        detaiRequest="";
        detaiSpecialized="";
    }

    public Detai(int projectInstructorid) {
        this.projectInstructorid = projectInstructorid;
    }

    public Detai(Users users, String projectName, String projectContentlink, int projectInstructorid, Integer projectProgress, String projectStartdate, Boolean projectStatus, String projectDescription, Integer projectViewcount, Integer projectPagecount, Boolean projectCancel, Boolean isdelete, String deleteDate, Integer deleteUserid, String detaiResult, String detaiRequest, String detaiSpecialized, Set<Tiendo> tiendos) {
        this.users = users;
        this.projectName = projectName;
        this.projectContentlink = projectContentlink;
        this.projectInstructorid = projectInstructorid;
        this.projectProgress = projectProgress;
        this.projectStartdate = projectStartdate;
        this.projectStatus = projectStatus;
        this.projectDescription = projectDescription;
        this.projectViewcount = projectViewcount;
        this.projectPagecount = projectPagecount;
        this.projectCancel = projectCancel;
        this.isdelete = isdelete;
        this.deleteDate = deleteDate;
        this.deleteUserid = deleteUserid;
        this.detaiResult = detaiResult;
        this.detaiRequest = detaiRequest;
        this.detaiSpecialized = detaiSpecialized;
        this.tiendos = tiendos;
    }

    public Integer getProjectId() {
        return this.projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public String getProjectName() {
        return this.projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getProjectContentlink() {
        return this.projectContentlink;
    }

    public void setProjectContentlink(String projectContentlink) {
        this.projectContentlink = projectContentlink;
    }

    public int getProjectInstructorid() {
        return this.projectInstructorid;
    }

    public void setProjectInstructorid(int projectInstructorid) {
        this.projectInstructorid = projectInstructorid;
    }

    public Integer getProjectProgress() {
        return this.projectProgress;
    }

    public void setProjectProgress(Integer projectProgress) {
        this.projectProgress = projectProgress;
    }

    public String getProjectStartdate() {
        return this.projectStartdate;
    }

    public void setProjectStartdate(String projectStartdate) {
        this.projectStartdate = projectStartdate;
    }

    public Boolean getProjectStatus() {
        return this.projectStatus;
    }

    public void setProjectStatus(Boolean projectStatus) {
        this.projectStatus = projectStatus;
    }

    public String getProjectDescription() {
        return this.projectDescription;
    }

    public void setProjectDescription(String projectDescription) {
        this.projectDescription = projectDescription;
    }

    public Integer getProjectViewcount() {
        return this.projectViewcount;
    }

    public void setProjectViewcount(Integer projectViewcount) {
        this.projectViewcount = projectViewcount;
    }

    public Integer getProjectPagecount() {
        return this.projectPagecount;
    }

    public void setProjectPagecount(Integer projectPagecount) {
        this.projectPagecount = projectPagecount;
    }

    public Boolean getProjectCancel() {
        return this.projectCancel;
    }

    public void setProjectCancel(Boolean projectCancel) {
        this.projectCancel = projectCancel;
    }

    public Boolean getIsdelete() {
        return this.isdelete;
    }

    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    public String getDeleteDate() {
        return this.deleteDate;
    }

    public void setDeleteDate(String deleteDate) {
        this.deleteDate = deleteDate;
    }

    public Integer getDeleteUserid() {
        return this.deleteUserid;
    }

    public void setDeleteUserid(Integer deleteUserid) {
        this.deleteUserid = deleteUserid;
    }

    public String getDetaiResult() {
        return this.detaiResult;
    }

    public void setDetaiResult(String detaiResult) {
        this.detaiResult = detaiResult;
    }

    public String getDetaiRequest() {
        return this.detaiRequest;
    }

    public void setDetaiRequest(String detaiRequest) {
        this.detaiRequest = detaiRequest;
    }

    public String getDetaiSpecialized() {
        return this.detaiSpecialized;
    }

    public void setDetaiSpecialized(String detaiSpecialized) {
        this.detaiSpecialized = detaiSpecialized;
    }

    public Set<Tiendo> getTiendos() {
        return this.tiendos;
    }

    public void setTiendos(Set<Tiendo> tiendos) {
        this.tiendos = tiendos;
    }

}
