package hibernate.entity;
// Generated Jun 4, 2017 6:40:18 PM by Hibernate Tools 4.3.1



/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer messageId;
     private Integer messageProjectId;
     private Integer messageStudentId;
     private Integer messageLecturerId;
     private Integer messageType;
     private Integer messageStatus;
     private String messageNote;
     private Integer messageIsDelete;

    public Message() {
    }

    public Message(Integer messageProjectId, Integer messageStudentId, Integer messageLecturerId, Integer messageType, Integer messageStatus, String messageNote, Integer messageIsDelete) {
       this.messageProjectId = messageProjectId;
       this.messageStudentId = messageStudentId;
       this.messageLecturerId = messageLecturerId;
       this.messageType = messageType;
       this.messageStatus = messageStatus;
       this.messageNote = messageNote;
       this.messageIsDelete = messageIsDelete;
    }
   
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }
    public Integer getMessageProjectId() {
        return this.messageProjectId;
    }
    
    public void setMessageProjectId(Integer messageProjectId) {
        this.messageProjectId = messageProjectId;
    }
    public Integer getMessageStudentId() {
        return this.messageStudentId;
    }
    
    public void setMessageStudentId(Integer messageStudentId) {
        this.messageStudentId = messageStudentId;
    }
    public Integer getMessageLecturerId() {
        return this.messageLecturerId;
    }
    
    public void setMessageLecturerId(Integer messageLecturerId) {
        this.messageLecturerId = messageLecturerId;
    }
    public Integer getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }
    public Integer getMessageStatus() {
        return this.messageStatus;
    }
    
    public void setMessageStatus(Integer messageStatus) {
        this.messageStatus = messageStatus;
    }
    public String getMessageNote() {
        return this.messageNote;
    }
    
    public void setMessageNote(String messageNote) {
        this.messageNote = messageNote;
    }
    public Integer getMessageIsDelete() {
        return this.messageIsDelete;
    }
    
    public void setMessageIsDelete(Integer messageIsDelete) {
        this.messageIsDelete = messageIsDelete;
    }




}


