package hibernate.entity;
// Generated Jun 4, 2017 6:40:18 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Tiendo generated by hbm2java
 */
public class Tiendo implements java.io.Serializable {

    public static final String TDNAME = "";
    public static final String TDCREATEDATE = "";
    public static final int USERID = 0;
    public static final String TDDESCRIPTION = "";
    public static final Boolean TDSTATUS = true;
    public static final Integer TDPROCESS = 0;
    public static final Boolean ISDELETE = false;
    public static final String DELETEDATE = "";
    public static final Integer DELETEUSERID = 0;
    public static final String TDRESULT = "";
    public static final String TDREQUEST = "";
    public static final String TDENDDATE = "";
    public static final String TDNOTE = "";

    private Integer tdId;
    private Detai detai;
    private String tdName;
    private String tdCreatedate;
    private int userId;
    private String tdDescription;
    private Boolean tdStatus;
    private Integer tdProcess;
    private Boolean isdelete;
    private String deleteDate;
    private Integer deleteUserid;
    private String tdResult;
    private String tdRequest;
    private String tdEnddate;
    private String tdNote;
    private Set<Comments> commentses = new HashSet<Comments>(0);

    public Tiendo() {
        this(TDNAME, TDCREATEDATE, 0, TDDESCRIPTION, TDSTATUS, TDPROCESS, ISDELETE, DELETEDATE, DELETEUSERID, TDRESULT, TDREQUEST, TDENDDATE, TDNOTE);
    }

    public Tiendo(Detai detai, int userId) {
        this.detai = detai;
        this.userId = userId;
        
    }

    public Tiendo(String tdName, String tdCreatedate, int userId, String tdDescription, Boolean tdStatus, Integer tdProcess, Boolean isdelete, String deleteDate, Integer deleteUserid, String tdResult, String tdRequest, String tdEnddate, String tdNote) {
        this.detai = detai;
        this.tdName = tdName;
        this.tdCreatedate = tdCreatedate;
        this.userId = userId;
        this.tdDescription = tdDescription;
        this.tdStatus = tdStatus;
        this.tdProcess = tdProcess;
        this.isdelete = isdelete;
        this.deleteDate = deleteDate;
        this.deleteUserid = deleteUserid;
        this.tdResult = tdResult;
        this.tdRequest = tdRequest;
        this.tdEnddate = tdEnddate;
        this.tdNote = tdNote;
        this.commentses = commentses;
    }

    public Integer getTdId() {
        return this.tdId;
    }

    public void setTdId(Integer tdId) {
        this.tdId = tdId;
    }

    public Detai getDetai() {
        return this.detai;
    }

    public void setDetai(Detai detai) {
        this.detai = detai;
    }

    public String getTdName() {
        return this.tdName;
    }

    public void setTdName(String tdName) {
        this.tdName = tdName;
    }

    public String getTdCreatedate() {
        return this.tdCreatedate;
    }

    public void setTdCreatedate(String tdCreatedate) {
        this.tdCreatedate = tdCreatedate;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getTdDescription() {
        return this.tdDescription;
    }

    public void setTdDescription(String tdDescription) {
        this.tdDescription = tdDescription;
    }

    public Boolean getTdStatus() {
        return this.tdStatus;
    }

    public void setTdStatus(Boolean tdStatus) {
        this.tdStatus = tdStatus;
    }

    public Integer getTdProcess() {
        return this.tdProcess;
    }

    public void setTdProcess(Integer tdProcess) {
        this.tdProcess = tdProcess;
    }

    public Boolean getIsdelete() {
        return this.isdelete;
    }

    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    public String getDeleteDate() {
        return this.deleteDate;
    }

    public void setDeleteDate(String deleteDate) {
        this.deleteDate = deleteDate;
    }

    public Integer getDeleteUserid() {
        return this.deleteUserid;
    }

    public void setDeleteUserid(Integer deleteUserid) {
        this.deleteUserid = deleteUserid;
    }

    public String getTdResult() {
        return this.tdResult;
    }

    public void setTdResult(String tdResult) {
        this.tdResult = tdResult;
    }

    public String getTdRequest() {
        return this.tdRequest;
    }

    public void setTdRequest(String tdRequest) {
        this.tdRequest = tdRequest;
    }

    public String getTdEnddate() {
        return this.tdEnddate;
    }

    public void setTdEnddate(String tdEnddate) {
        this.tdEnddate = tdEnddate;
    }

    public String getTdNote() {
        return this.tdNote;
    }

    public void setTdNote(String tdNote) {
        this.tdNote = tdNote;
    }

    public Set<Comments> getCommentses() {
        return this.commentses;
    }

    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }

}
