package hibernate.entity;
// Generated Apr 24, 2017 1:01:57 PM by Hibernate Tools 4.3.1



/**
 * Tiendo generated by hbm2java
 */
public class Tiendo  implements java.io.Serializable {


     private Integer tdId;
     private String tdName;
     private String tdCreatedate;
     private int tdProjectid;
     private int tdParentid;
     private String tdDescription;
     private Boolean tdStatus;
     private Integer tdProcess;

    public Tiendo() {
    }

	
    public Tiendo(int tdProjectid, int tdParentid) {
        this.tdProjectid = tdProjectid;
        this.tdParentid = tdParentid;
    }
    public Tiendo(String tdName, String tdCreatedate, int tdProjectid, int tdParentid, String tdDescription, Boolean tdStatus, Integer tdProcess) {
       this.tdName = tdName;
       this.tdCreatedate = tdCreatedate;
       this.tdProjectid = tdProjectid;
       this.tdParentid = tdParentid;
       this.tdDescription = tdDescription;
       this.tdStatus = tdStatus;
       this.tdProcess = tdProcess;
    }
   
    public Integer getTdId() {
        return this.tdId;
    }
    
    public void setTdId(Integer tdId) {
        this.tdId = tdId;
    }
    public String getTdName() {
        return this.tdName;
    }
    
    public void setTdName(String tdName) {
        this.tdName = tdName;
    }
    public String getTdCreatedate() {
        return this.tdCreatedate;
    }
    
    public void setTdCreatedate(String tdCreatedate) {
        this.tdCreatedate = tdCreatedate;
    }
    public int getTdProjectid() {
        return this.tdProjectid;
    }
    
    public void setTdProjectid(int tdProjectid) {
        this.tdProjectid = tdProjectid;
    }
    public int getTdParentid() {
        return this.tdParentid;
    }
    
    public void setTdParentid(int tdParentid) {
        this.tdParentid = tdParentid;
    }
    public String getTdDescription() {
        return this.tdDescription;
    }
    
    public void setTdDescription(String tdDescription) {
        this.tdDescription = tdDescription;
    }
    public Boolean getTdStatus() {
        return this.tdStatus;
    }
    
    public void setTdStatus(Boolean tdStatus) {
        this.tdStatus = tdStatus;
    }
    public Integer getTdProcess() {
        return this.tdProcess;
    }
    
    public void setTdProcess(Integer tdProcess) {
        this.tdProcess = tdProcess;
    }




}


