package hibernate.entity;
// Generated Apr 24, 2017 1:01:57 PM by Hibernate Tools 4.3.1

import hibernate.util.HibernateUtil;
import java.util.ArrayList;
import java.util.List;
import javax.servlet.jsp.tagext.TryCatchFinally;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

    private Integer userId;
    private String userName;
    private String userPassword;
    private String userFullname;
    private String userDateofbirth;
    private String userGender;
    private String userFaculty;
    private String userDegree;
    private String userAvatar;
    private Boolean userActive;
    private String userAddress;
    private String userEmail;
    private String userMobile;
    private String userReligion;
    private Integer userType;
    private String userClass;

    public Users() {
    }

    public Users(String userName, String userPassword) {
        this.userName = userName;
        this.userPassword = userPassword;
    }

    public Users(String userName, String userPassword, String userFullname, String userDateofbirth, String userGender, String userFaculty, String userDegree, String userAvatar, Boolean userActive, String userAddress, String userEmail, String userMobile, String userReligion, Integer userType, String userClass) {
        this.userName = userName;
        this.userPassword = userPassword;
        this.userFullname = userFullname;
        this.userDateofbirth = userDateofbirth;
        this.userGender = userGender;
        this.userFaculty = userFaculty;
        this.userDegree = userDegree;
        this.userAvatar = userAvatar;
        this.userActive = userActive;
        this.userAddress = userAddress;
        this.userEmail = userEmail;
        this.userMobile = userMobile;
        this.userReligion = userReligion;
        this.userType = userType;
        this.userClass = userClass;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserPassword() {
        return this.userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public String getUserFullname() {
        return this.userFullname;
    }

    public void setUserFullname(String userFullname) {
        this.userFullname = userFullname;
    }

    public String getUserDateofbirth() {
        return this.userDateofbirth;
    }

    public void setUserDateofbirth(String userDateofbirth) {
        this.userDateofbirth = userDateofbirth;
    }

    public String getUserGender() {
        return this.userGender;
    }

    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }

    public String getUserFaculty() {
        return this.userFaculty;
    }

    public void setUserFaculty(String userFaculty) {
        this.userFaculty = userFaculty;
    }

    public String getUserDegree() {
        return this.userDegree;
    }

    public void setUserDegree(String userDegree) {
        this.userDegree = userDegree;
    }

    public String getUserAvatar() {
        return this.userAvatar;
    }

    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar;
    }

    public Boolean getUserActive() {
        return this.userActive;
    }

    public void setUserActive(Boolean userActive) {
        this.userActive = userActive;
    }

    public String getUserAddress() {
        return this.userAddress;
    }

    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    public String getUserEmail() {
        return this.userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getUserMobile() {
        return this.userMobile;
    }

    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }

    public String getUserReligion() {
        return this.userReligion;
    }

    public void setUserReligion(String userReligion) {
        this.userReligion = userReligion;
    }

    public Integer getUserType() {
        return this.userType;
    }

    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    public String getUserClass() {
        return this.userClass;
    }

    public void setUserClass(String userClass) {
        this.userClass = userClass;
    }

    public static void main(String[] args) {
        SessionFactory factoty = HibernateUtil.getSessionFactory();
        Session session = factoty.getCurrentSession();
        List<Users> resuilt = null;
        try {
            session.beginTransaction();
            String hql = "FROM Users as nv";
            Query query = session.createQuery(hql);
            resuilt = query.list();
        } catch (Exception e) {
            e.printStackTrace();
        }
        for(Users i:resuilt){
            System.out.println(i.getUserName());
        }
    }

}
